port: 5000

# define duration between each dashboard rotation (seconds)
rotationDuration: 10
# define the interval used by Moza√Øk Bus to call registered APIs
apisPollInterval: 100000

extension:   &extension github
github_user: &github_user plouc
github_org:  &github_org  ekino
github_repo: &github_repo plouc/mozaik

dashboards:
- title:   GitHub Dashboard Demo 1 (mozaik-ext-github)
  columns: 3
  rows:    3
  widgets:
  - extension:    *extension
    widget:       UserBadge
    user:         *github_user
    columns:      1
    rows:         1
    x:            0
    y:            0

  - extension:    *extension
    widget:       RepoBadge
    repository:   *github_repo
    columns:      1
    rows:         1
    x:            1
    y:            0

  - extension:    *extension
    widget:       OrgBadge
    organization: *github_org
    columns:      1
    rows:         1
    x:            2
    y:            0

  - extension:    *extension
    widget:       Branches
    repository:   *github_repo
    columns:      1
    rows:         1
    x:            0
    y:            1

  - extension:    *extension
    widget:       RepoCommitActivityLine
    repository:   *github_repo
    columns:      2
    rows:         1
    x:            1
    y:            1

  - extension:    *extension
    widget:       RepoTrafficViewsHistogram
    repository:   *github_repo
    rows:         1
    columns:      2
    x:            0
    y:            2

  - extension:    mozaik
    widget:       Inspector
    columns:      1
    rows:         1
    x:            2
    y:            2

- title:   GitHub Dashboard Demo 2 (mozaik-ext-github)
  columns: 3
  rows:    3
  widgets:
  - extension:    *extension
    widget:       RepoContributorsStats
    repository:   *github_repo
    columns:      1
    rows:         1
    x:            0
    y:            0

  - extension:    *extension
    widget:       PullRequests
    repository:   *github_repo
    columns:      1
    rows:         1
    x:            1
    y:            0

  - extension:    *extension
    widget:       Status
    columns:      1
    rows:         1
    x:            2
    y:            0

  - extension:    *extension
    widget:       RepoTrafficViewsLine
    repository:   *github_repo
    rows:         1
    columns:      2
    x:            0
    y:            1

  - extension:    *extension
    widget:       RepoBadge
    repository:   *github_repo
    columns:      1
    rows:         1
    x:            2
    y:            1

  - extension:    mozaik
    widget:       Inspector
    columns:      1
    rows:         1
    x:            0
    y:            2

  - extension:    *extension
    widget:       RepoTrafficClonesHistogram
    repository:   *github_repo
    columns:      2
    rows:         1
    x:            1
    y:            2
