host: 0.0.0.0
port: 5000

# define duration between each dashboard rotation (ms)
rotationDuration: 8000

# define the interval used by Moza√Øk Bus to call registered APIs
apisPollInterval: 100000

extension: &extension gitlab
gitlabProject: &gitlabProject gitlab-org/gitlab-ci-multi-runner

dashboards:
- title:   GitLab Demo
  columns: 3
  rows:    3
  widgets:
    -
      extension: *extension
      widget:    Project
      project:   *gitlabProject
      columns:   1
      rows:      1
      x:         0
      y:         0
    -
      extension: *extension
      widget:    ProjectMembers
      project:   *gitlabProject
      columns:   1
      rows:      1
      x:         1
      y:         2
    -
      extension: *extension
      widget:    ProjectContributors
      project:   *gitlabProject
      columns:   1
      rows:      1
      x:         1
      y:         1
#    - type:    gitlab.merge_requests_gauge
#      project: *gitlabProject
#      columns: 1
#      rows:    1
#      x:       2
#      y:       0
    -
      extension: *extension
      widget:    BuildHistory
      project:   *gitlabProject
      columns:   1
      rows:      2
      x:         0
      y:         1
    -
      extension: *extension
      widget:    Branches
      project:   *gitlabProject
      columns:   1
      rows:      2
      x:         2
      y:         1
    -
      extension: *extension
      widget:    BuildHistogram
      project:   *gitlabProject
      columns:   2
      rows:      1
      x:         1
      y:         0
